server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ticket
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    addresses: localhost:5672
    username: user
    password: user
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 5
          max-interval: 10s
          multiplier: 2
        missing-queues-fatal: false

rabbitmq:
  dlq:
    order:
      name: create_order_dlq
      exchange: create_order_dlq_ex
      routing-key: create_order_dlq_rk
  queue:
    order:
      name: create_order_q
      exchange: create_order_q_ex
      routing-key: create_order_q_rk
