server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    addresses: localhost:5672
    username: user
    password: user

rabbitmq:
  queue:
    order:
      name: create_order_q
